activation: torch.nn.LeakyReLU()
average: weighted
base_encoder: paraphrase-mpnet-base-v2
classification: multilabel
criterion: torch.nn.BCEWithLogitsLoss(reduction='none')
data_path: KeyClassReproduce/scripts/data/
dataset: mimic
device: cuda
end_model_batch_size: 128 # Make 128 in Final run
end_model_epochs: 20
end_model_lr: 1e-4
end_model_patience: 3
end_model_weight_decay: 1e-4
h_sizes:
- 768
- 19 # Change to 19 in final run
label_model: data_programming
label_model_lr: 0.01
label_model_n_epochs: 100
max_num: 500
min_df: 0.001
model_path: KeyClassReproduce/models/mimic/
n_bootstrap: 100
n_classes: 19 # Change to 19 in final run
n_jobs: 10
ngram_range: !!python/tuple
- 1
- 3
normalize_embeddings: false
preds_path: KeyClassReproduce/results/mimic/
q_update_interval: 50
results_path: KeyClassReproduce/results/mimic/
self_train_batch_size: 16
self_train_lr: 1e-6
self_train_patience: 8
self_train_thresh: 1-2e-3
self_train_weight_decay: 1e-4
show_progress_bar: true
target_00: infections, parasitic, bacterial, malaria, viral
target_01: neoplasms, malignant, tumor, carcinoma, chemotherapy, benign, metastatic, cancer
target_02: endocrine, nutritional, metabolic, thyroid, diabetes, autoimmune, vitamin deficiency
target_03: blood, blood-forming organs, anemia, leukemia, hemophilia, thrombocytopenia, hemolytic
target_04: mental disorders, disorder, depression, anxiety, schizophrenia, bipolar
target_05: nervous system, parkinson, neuropathy
target_06: sense organs, sensorineural, hearing, vision, macular degeneration, glaucoma
target_07: circulatory system, coronary, artery, heart, hypertension, myocardial
target_08: respiratory system, asthma, pneumonia, bronchitis, emphysema, lung, obstructive
target_09: digestive system, hepatitis C, ulcerative colitis, gastroesophageal reflux
target_10: genitourinary system, kidney, urinary, erectile
target_11: pregnancy, childbirth, mother, mom, fetus, fetal, eclampsia
target_12: skin, subcutaneous tissue, cellulitis, melanoma, acne, eczema
target_13: musculoskeletal system, connective tissue, arthritis, osteoporosis, fibromyalgia
target_14: congenital anomalies, down syndrome, cleft palate
target_15: perinatal period conditions, neonatal jaundice, premature
target_16: injury and poisoning, toxic, burn, concussion
target_17: external causes of injury, fall, drowning, motor vehicle
target_18: supplementary
topk: 50
use_custom_encoder: false
use_noise_aware_loss: true
