activation: torch.nn.LeakyReLU()
average: weighted
base_encoder: paraphrase-mpnet-base-v2
classification: standard
criterion: torch.nn.BCEWithLogitsLoss(reduction='none')
data_path: KeyClassReproduce/scripts/data/
dataset: smallmimic
device: cuda
end_model_batch_size: 128
end_model_epochs: 1
end_model_lr: 1e-4
end_model_patience: 3
end_model_weight_decay: 1e-4
h_sizes:
- 768
- 3
label_model: data_programming
label_model_lr: 0.01
label_model_n_epochs: 1
max_num: 500
min_df: 0.001
model_path: KeyClassReproduce/models/smallmimic/
n_bootstrap: 100
n_classes: 2
n_jobs: 10
ngram_range: !!python/tuple
- 1
- 3
normalize_embeddings: false
preds_path: KeyClassReproduce/results/smallmimic/
q_update_interval: 50
results_path: KeyClassReproduce/results/smallmimic/
self_train_batch_size: 16
self_train_lr: 1e-6
self_train_patience: 8
self_train_thresh: 1-2e-3
self_train_weight_decay: 1e-4
show_progress_bar: true
target_00: infections, malaria, virus,bacilli, bacteriological, histological, tubercle, tuberculosis, tubercle bacilli
topk: 20
use_custom_encoder: false
use_noise_aware_loss: true
